"""add users, pages, edits tables

Revision ID: 29c3215700d8
Revises: 
Create Date: 2023-08-07 14:33:08.986056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c3215700d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pages_id', sa.Integer(), nullable=True),
    sa.Column('diff', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pages_id'], ['pages.id'], name=op.f('fk_edits_pages_id_pages')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_edits_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edits')
    op.drop_table('users')
    op.drop_table('pages')
    # ### end Alembic commands ###
