"""added title to pages, got rid of time an fixed typo in edits

Revision ID: 642225ff6fe5
Revises: 29c3215700d8
Create Date: 2023-08-07 14:40:12.428425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642225ff6fe5'
down_revision = '29c3215700d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_edits_pages_id_pages', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_edits_page_id_pages'), 'pages', ['page_id'], ['id'])
        batch_op.drop_column('pages_id')
        batch_op.drop_column('time')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('edits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('pages_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_edits_page_id_pages'), type_='foreignkey')
        batch_op.create_foreign_key('fk_edits_pages_id_pages', 'pages', ['pages_id'], ['id'])
        batch_op.drop_column('page_id')

    # ### end Alembic commands ###
