"""add time to edit

Revision ID: e527e094617f
Revises: c691a285e17f
Create Date: 2023-08-10 16:37:17.691498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e527e094617f'
down_revision = 'c691a285e17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edits', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
